Repository mitul382/Python-projects, pull requests merged in 2022-10, with the labels that each got.

#4 Create day2.py
  day2.py
Labels: hacktoberfest

#3 Create Day1.py
  Day1.py
Labels: hacktoberfest

#1 Create basic.py
  basic.py
Labels: hacktoberfest

#2 Create brand name generator.py
  brand name generator.py
Labels: hacktoberfest

#5 Update basic.py
  basic.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#8 Update day2.py
  day2.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#7 Update brand name generator.py
  brand name generator.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#6 Update Day1.py
  Day1.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#12 Update README.md
  README.md
Labels: HACKTOBERFEST-ACCEPTED

#11 Update basic.py
  basic.py
Labels: HACKTOBERFEST-ACCEPTED

#10 Update Day1.py
  Day1.py
Labels: HACKTOBERFEST-ACCEPTED

#9 Update day2.py
  day2.py
Labels: HACKTOBERFEST-ACCEPTED

#18 Update day2.py
  day2.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#17 Added quadratic_formula_calc.py file
  quadratic_formula_calc.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#16 Update Day1.py
  Day1.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#15 Update Day1.py
  Day1.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#13 Update day2.py
  day2.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#20 Create tip calculator.py
  tip calculator.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#23 Create rock paper game.py
  rock paper game.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#22 Added fizzbuzz.py
  fizzbuzz.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#21 Create tressure island.py
  tressure island.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#24 Update brand name generator.py
  brand name generator.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#25 Update tressure island.py
  tressure island.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#27 Update Day1.py
  Day1.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#26 Update basic.py
  basic.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#43 Create Code_16.py
  Code_16.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#42 Create Code_15.py
  Code_15.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#41 Create Code_14.py
  Code_14.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#40 Create Code_13.py
  Code_13.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#39 Create Code_12.py
  Code_12.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#38 Create Code_11.py
  Code_10.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#37 Create Code_10.py
  Code_10.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#36 Create Code_9.py
  Code_9.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#35 Create Code_8.py
  Code_8.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#34 Create Code_7.py
  Code_7.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#33 Create Code_6.py
  Code_6.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#32 Create Code_5.py
  Code_5.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#31 Create Code_4.py
  Code_4.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#30 Create Code_3.py
  Code_3.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#29 Create Code_2.py
  Code_2.py
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED
